CREATE USER forum WITH
    LOGIN
    NOSUPERUSER
    INHERIT
    NOCREATEDB
    NOCREATEROLE
    NOREPLICATION
    CONNECTION LIMIT -1
    PASSWORD 'forum';

CREATE DATABASE forum
    WITH
    OWNER = forum
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;